settings:
  legacy:
    force: false

schema:
  - name: sqlboiler-example
    path: .
    commands:
      install:
        status: true
        method: go build -o /go/bin/app
      run:
        status: true
        method: /go/bin/app
    watcher:
      extensions:
        - go
      paths:
        - /
      ignore:
        paths:
          - .git
          - .realize
          - .data
          - vendor
          - sql
